name: CI

on:
  push:
    branches: [ main ]
    paths:
      - apple-maps-server-kotlin/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/gradle-build-action@v2.12.0

      - name: Build
        run: ./gradlew build
